### ISSUE TITLE
「Webビューの読み込みエラー」によりipynbファイルが表示されない

### ISSUE THREAD

**Issue by CLRafaelR** [ykunisato/tutorial-HGF-cpsycourse2023#1]
[「GithubのCodespaces上で実行する」の指示](https://github.com/ykunisato/tutorial-HGF-cpsycourse2023#1github%E3%81%AEcodespaces%E4%B8%8A%E3%81%A7%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B)に従い，Codespacesの立ち上げまではできたのですが，「Webビューの読み込みエラー: Error: Could not register service workers: NotSupportedEditor」によりipynbファイルが表示されないという問題が起きています。CodespacesはGoogle Chromeで閲覧しており，ローカルのVS Codeは開いていない状況で発生しています。Codespacesを開いているGoogle Chromeのタブを再読み込みしても，同じ問題が続きます。また，CodespacesをDeleteして再度立ち上げなおした時も，同じ問題が起きます。この問題の解決にあたり，どのように対処したらよろしいでしょうか。ワークショップ前日に大変恐縮ではございますが，もし先生の方でご存じのことがございましたら何卒ご教示いただきたくよろしくお願い申し上げます。

![image](https://user-images.githubusercontent.com/42314553/221811462-9335e68e-97dd-47aa-961f-24590e5d8bc2.png)

**Comment by ykunisato** [comment]
これは，初めて見るエラーです。コンテナを削除するとうまくいくことが多いですが，それもされておられますね。
なんとなく画面を見ていると，codespacesにいくつか拡張をいれておられるようにも感じます。そのどれかが悪さをしている可能性はあるのですが，自信はありません。

**Comment by CLRafaelR** [comment]
ご返信ありがとうございます。codespacesに入った拡張機能が原因になりうるとのこと，ご教示ありがとうございます。投稿時点で開いたコンテナについては，既に削除してしまったため，実際にどのような拡張機能があったのか分からなくなっておりますが，少なくとも私自身は手動で拡張機能をインストールはしておりませんでした。

また，このコメント時点で開いているコンテナには，拡張機能が入っておりませんが，このコンテナでも問題が続いております。
![image](https://user-images.githubusercontent.com/42314553/221898027-4d3d96b5-06a7-4bbd-ac69-31d7c3863cee.png)

原因はいまだ分かりませんが，おそらく私の端末・環境等によるものかと存じますので，お見捨ておきいただければと存じます。

お騒がせしましたことお詫び申し上げますとともに，ご返信重ねて御礼申し上げます。
